from tkinter import *
root= Tk()
root.geometry("827x827")
root.title("Calculator in tkinter")
root.configure(background="lightgrey")

def click(event):
    text=event.widget.cget("text")
    if(text=="C"):
        scr_value.set("")
        screen.update()
    elif(text=="="):
        if(scr_value.get().isdigit()):
            value= int(scr_value.get())
        else:
            value = eval(scr_value.get())
        scr_value.set(value)
        screen.update()
    else:
        scr_value.set(scr_value.get()+ text)
        screen.update()

scr_value= StringVar()
scr_value.set("")
screen= Entry(root, textvariable=scr_value,font="Lucida 24 bold")
screen.pack(fill=X, padx=18, pady=12, ipadx=6, ipady=6)

f1= Frame(root,height=200, width=400)
b1= Button(f1, text="7",font="timesnewroman 34 bold")
b1.bind("<Button-1>",click)
b1.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
b2= Button(f1, text="8",font="timesnewroman 34 bold")
b2.bind("<Button-1>",click)
b2.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
b3= Button(f1, text="9",font="timesnewroman 34 bold")
b3.bind("<Button-1>",click)
b3.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
f1.pack()

f2= Frame(root,height=200, width=400)
b4= Button(f2, text="4",font="timesnewroman 34 bold")
b4.bind("<Button-1>",click)
b4.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
b5= Button(f2, text="5",font="timesnewroman 34 bold")
b5.bind("<Button-1>",click)
b5.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
b6= Button(f2, text="6",font="timesnewroman 34 bold")
b6.bind("<Button-1>",click)
b6.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
f2.pack()

f3= Frame(root,height=200, width=400)
b7= Button(f3, text="1",font="timesnewroman 34 bold")
b7.bind("<Button-1>",click)
b7.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
b8= Button(f3, text="2",font="timesnewroman 34 bold")
b8.bind("<Button-1>",click)
b8.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
b9= Button(f3, text="3",font="timesnewroman 34 bold")
b9.bind("<Button-1>",click)
b9.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
f3.pack()

f4= Frame(root,height=200, width=400)
b10= Button(f4, text="0",font="timesnewroman 34 bold")
b10.bind("<Button-1>",click)
b10.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
b11= Button(f4, text=".",font="timesnewroman 34 bold")
b11.bind("<Button-1>",click)
b11.pack(side=LEFT,padx=18,pady=6,ipadx=15,ipady=6)
b12= Button(f4, text="=",font="timesnewroman 34 bold")
b12.bind("<Button-1>",click)
b12.pack(side=LEFT,padx=18,pady=6,ipadx=14,ipady=6)
f4.pack()

f5= Frame(root,height=200, width=400)
b13= Button(f5, text="/",font="timesnewroman 34 bold")
b13.bind("<Button-1>",click)
b13.pack(side=LEFT,padx=18,pady=6,ipadx=15,ipady=6)
b14= Button(f5, text="*",font="timesnewroman 34 bold")
b14.bind("<Button-1>",click)
b14.pack(side=LEFT,padx=18,pady=6,ipadx=15,ipady=6)
b15= Button(f5, text="+",font="timesnewroman 34 bold")
b15.bind("<Button-1>",click)
b15.pack(side=LEFT,padx=18,pady=6,ipadx=15,ipady=6)
f5.pack()

f6= Frame(root,height=200, width=400)
b16= Button(f6, text="-",font="timesnewroman 34 bold")
b16.bind("<Button-1>",click)
b16.pack(side=LEFT,padx=18,pady=6,ipadx=12,ipady=6)
b17= Button(f6, text="%",font="timesnewroman 34 bold")
b17.bind("<Button-1>",click)
b17.pack(side=LEFT,padx=18,pady=6,ipadx=10,ipady=6)
b18= Button(f6, text="C",font="timesnewroman 34 bold")
b18.bind("<Button-1>",click)
b18.pack(side=LEFT,padx=18,pady=6,ipadx=10,ipady=6)
f6.pack()

root.mainloop()